version: '2.4'
services:
    nginx:
        container_name: hotels_nginx
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            -   ./:/var/www
        ports:
            -   "8099:80"
        links:
            -   php-fpm
    php-fpm:
        container_name: hotels_php_fpm
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            -   ./:/var/www
        links:
            - mysql
#            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    php-cli:
        container_name: hotels_php_cli
        build:
            context: ./
            dockerfile: docker/php-cli.docker
            args:
                UID: 1000
                GID: 1000
        volumes:
            - ./:/var/www
            - "~/.ssh/:/home/www-data/.ssh/"
        links:
            - mysql
#            - redis
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        tty: true
    mysql:
        container_name: hotels_mysql
        command: --authentication-policy=mysql_native_password
        build:
            context: ./
            dockerfile: docker/mysql.docker
        volumes:
            -   ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            -   "33063:3306"
#    redis:
#        image: redis:6.2
#        ports:
#            -   "6380:6379"
    rabbitmq:
        container_name: hotels_rabbitmq
        image: rabbitmq:management-alpine
        init: true
        ports:
            - 15673:15672
            - 5673:5672
        environment:
            RABBITMQ_DEFAULT_VHOST: /
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-password}
        hostname: rabbitmq

